import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const univers = localFont({
  src: [
    { path: "../assets/univers/UniversRegular.ttf", weight: "400", style: "normal" },
    { path: "../assets/univers/UniversBold.ttf", weight: "700", style: "normal" },
    { path: "../assets/univers/UniversCnRg.ttf", weight: "400", style: "normal" },
    { path: "../assets/univers/UniversCnBold.ttf", weight: "700", style: "normal" },
  ],
  variable: "--font-univers",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${univers.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
